name: Update Guestbook

on:
  schedule:
    - cron: '*/5 * * * *'
  issues:
    types: [opened, edited, deleted, labeled]
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  update-guestbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Guestbook
        uses: jonico/guestbook-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'Guestbook Entry'
          max: 20
          readme: './README.md'
          section: 'guestbook'
